### ISSUE TITLE
Everything is Positive

### ISSUE THREAD

**Issue by ivbac** [ckinateder/abraham#1]
Nice Module, but I'm getting Positive Analysis on loosing stock news... plus this 

site-packages\dateutil\parser\_parser.py:1213: UnknownTimezoneWarning: tzname EDT identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.

**Comment by ckinateder** [comment]
Interesting. I'll take a look at it, I've definitely had negative cases. What search terms specifically are you mentioning? The datetime thing is something I'm looking to fix as well. I'll put a separate issue in.

**Comment by ivbac** [comment]
I just looked for stocks doing worst lately.
Window was 2 days back from 4/19.
Maybe if I did 5 - 10 days perhaps it would get better data volume to analyze?

**Comment by ckinateder** [comment]
Possibly. I'm going take a look at the algorithm and see what I can find.

**Comment by ckinateder** [comment]
@ivbac I changed some weights in the averages and such. It's more accurate now and the scores make more sense. I'm going to close the issue because I believe I have solved it but feel free to let me know if you find anything else. Thanks for your help!

**Comment by ivbac** [comment]
Thanks
